title: Chroma9
description: Musician, Voice Actor, Audio Engineer.
color: 0A0A0A

twitter: https://twitter.com/OfficialChroma9
youtube: https://www.youtube.com/Chroma9
bandcamp: https://chroma9.bandcamp.com/
soundcloud: https://soundcloud.com/Chroma9
spotify: https://open.spotify.com/artist/4pKo6ILFbitfEhqLALoamR
itunes: https://music.apple.com/us/artist/chroma9/1518505310
amazon: https://www.amazon.com/s?k=Chroma9&i=digital-music
